project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!quiz/*"

website:
  title: "MOVEL AI 2025-2026"
  bread-crumbs: true
  back-to-top-navigation: true

  navbar:
    right:
      - href: colofon.qmd
        text: Over deze module
  sidebar:
     - id: id-default
       style: "docked"
       search: true
       contents:        
         - href: index.qmd
           text: Home
         - href: start-hier/index.qmd
           text: ♥ Start hier           
         - href: inleiding/index.qmd
           text: Inleiding
         - href: ai-geletterdheid/
           text: AI-geletterdheid           
         - href: voorbeelden/
           text: Voorbeelden van AI
         - href: ai-in-het-onderwijs/
           text: AI in het onderwijs
         - href: de-mens-en-ai/
           text: De mens en AI 
         - href: ai-in-de-film/
           text: AI in de film 
         - href: toets-jezelf.qmd
           text: Test Jezelf!


     - id: id-inleiding
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: inleiding/index.qmd
           text: Inleiding
         - href: inleiding/wat-is-ai.qmd         
           text: Wat is AI?
         - href: inleiding/ai-onderwijs.qmd
           text: AI in het onderwijs
         - href: inleiding/ai-overheid.qmd
           text: AI bij de overheid
         - href: inleiding/jaws-effect.qmd
           text: Het Jaws-effect van AI
         - href: inleiding/klokhuis.qmd
           text: Het Klokhuis over AI
         - href: inleiding/lubach.qmd
           text: Lubach over AI
         - href: inleiding/nos-op-3.qmd
           text: NOS op 3 over AI  
         - href: inleiding/creativiteit.qmd
           text: Is AI slecht voor je creativiteit?


     - id: id-de-mens-en-ai
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: de-mens-en-ai/index.qmd
           text: De mens en AI
         - auto: "de-mens-en-ai/*.qmd"

     - id: id-voorbeelden
       style: "docked"
       search: true
       contents:        
         - href: index.qmd
           text: Home 
         - href: voorbeelden/index.qmd
           text: Voorbeelden van AI                             
         - auto: "voorbeelden/*.qmd"
     - id: id-ai-in-het-onderwijs
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: ai-in-het-onderwijs/index.qmd
           text: AI in het onderwijs
         - auto: "ai-in-het-onderwijs/*.qmd"
     - id: id-ai-geletterdheid
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: ai-geletterdheid/index.qmd
           text: Wat is AI-geletterdheid?
         - href: ai-geletterdheid/docentcompetenties.qmd
           text: Docentcompetenties
         - href: ai-geletterdheid/studentcompetenties.qmd
           text: Studentcompetenties
         - href: ai-geletterdheid/leidinggevendencompetenties.qmd
           text: Competenties leidinggevenden
         - href: ai-geletterdheid/experimenteren.qmd
           text: Experimenteren en professionaliseren

lang: nl

format:
  html:
    lightbox: auto
    toc: true
    theme:
      - cosmo
      - brand
    css: 
      - styles.css
      - webex.css
    include-after-body: webex.js
