project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!quiz/*"

format:
  html:
    link-external-newwindow: true
    link-external-icon: true  
    lightbox: auto
    toc: true
    theme:
      - cosmo
      - brand
    css: 
      - styles.css
      - webex.css
    include-after-body: webex.js     

website:
  title: "MOVEL AI 2025-2026"

  favicon: "media/MOVEL-icon.png"
  bread-crumbs: true
  back-to-top-navigation: true
  page-navigation: true
  cookie-consent: true

  navbar:
    right:
      - href: colofon.qmd
        text: Over deze module
  sidebar:
     - id: id-default
       logo: "media/MOVEL-icon.png"  
       style: "docked"
       search: true
       contents:        
         - href: index.qmd
           text: Home
         - href: start-hier/index.qmd
           text: ♥ Start hier           
         - href: inleiding/index.qmd
           text: Inleiding
         - href: ai-geletterdheid/
           text: AI-geletterdheid           
         - href: voorbeelden/
           text: Voorbeelden van AI
         - href: ai-in-het-onderwijs/
           text: AI in het onderwijs
         - href: vibecoding/
           text: Vibecoding
         - href: literatuur/
           text: Literatuur
         - href: de-mens-en-ai/
           text: De mens en AI 
         - href: ai-in-de-film/
           text: AI in de film 
         - href: toets-jezelf.qmd
           text: Test Jezelf!

     - id: id-inleiding
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: inleiding/index.qmd
           text: Inleiding
         - href: inleiding/wat-is-ai.qmd         
           text: Wat is AI?
         - href: inleiding/ai-onderwijs.qmd
           text: AI in het onderwijs
         - href: inleiding/ai-overheid.qmd
           text: AI bij de overheid
         - href: inleiding/jaws-effect.qmd
           text: Het Jaws-effect van AI
         - href: inleiding/klokhuis.qmd
           text: Het Klokhuis over AI
         - href: inleiding/lubach.qmd
           text: Lubach over AI
         - href: inleiding/nos-op-3.qmd
           text: NOS op 3 over AI  
         - href: inleiding/creativiteit.qmd
           text: Is AI slecht voor je creativiteit?


     - id: id-de-mens-en-ai
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: de-mens-en-ai/index.qmd
           text: De mens en AI
         - href: de-mens-en-ai/mens-en-technologie.qmd
           text: De mens centraal? 
         - href: de-mens-en-ai/betalen-voor-ai.qmd
           text: Betalen voor AI 
         - href: de-mens-en-ai/ethiek-en-richtlijnen.qmd
           text: Ethiek en Richtlijnen
         - href: de-mens-en-ai/ai-act.qmd
           text: De AI-Act
         - href: de-mens-en-ai/coded-bias.qmd
           text: Coded Bias
         - href: de-mens-en-ai/bias-praktijkvoorbeelden.qmd
           text: Bias in de praktijk
         - href: de-mens-en-ai/responsible-ai.qmd
           text: Responsible AI

     - id: id-voorbeelden
       style: "docked"
       search: true
       contents:        
         - href: index.qmd
           text: Home 
         - href: voorbeelden/index.qmd
           text: Voorbeelden van AI                             
         - auto: "voorbeelden/*.qmd"
     - id: id-ai-in-het-onderwijs
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: ai-in-het-onderwijs/index.qmd
           text: AI in het onderwijs
         - href: ai-in-het-onderwijs/china-voorbeeld.qmd
           text: China - een voorbeeld?
         - href: ai-in-het-onderwijs/feedbackfruits.qmd 
           text: Feedbackfruits
         - href: ai-in-het-onderwijs/lessonup.qmd
           text: LessonUp
         - href: ai-in-het-onderwijs/gradescope.qmd
           text: Gradescope 
         - href: ai-in-het-onderwijs/magicschool-ai.qmd
           text: MagicSchool AI 
         - href: ai-in-het-onderwijs/snappet-copilot.qmd
           text: Snappet Copilot 
         - href: ai-in-het-onderwijs/onzichtbare-ai.qmd
           text: Onzichtbare AI 
         - href: ai-in-het-onderwijs/nolai.qmd
           text: NOLAI
         - href: ai-in-het-onderwijs/kennisnet.qmd
           text: Kennisnet
         - href: ai-in-het-onderwijs/ai-teach.qmd
           text: AI-Teach
     - id: id-ai-geletterdheid
       style: "docked"
       search: true
       contents:
         - href: index.qmd
           text: Home
         - href: ai-geletterdheid/index.qmd
           text: Wat is AI-geletterdheid?
         - href: ai-geletterdheid/docentcompetenties.qmd
           text: Docentcompetenties
         - href: ai-geletterdheid/studentcompetenties.qmd
           text: Studentcompetenties
         - href: ai-geletterdheid/leidinggevendencompetenties.qmd
           text: Competenties leidinggevenden
         - href: ai-geletterdheid/experimenteren.qmd
           text: Experimenteren en professionaliseren

lang: nl


