---
title: "Het Jaws Effect voor AI"
lang: nl
sidebar: id-inleiding
---

Je zou kunnen stellen dat ook AI last heeft van het Jaws effect. Onderzoek toonde aan dat het, onterecht, negatieve beeld dat mensen hebben van haaien terug te leiden is naar het gegeven dat haaien in de meeste films als slecht, bloeddorstig of gevaarlijk worden neergezet. Finding Dory was daar een positieve uitzondering op.

Terwijl in werkelijkheid de haaien veel meer van ons te duchten hebben dan andersom. Ter vergelijking: jaarlijks zijn er wereldwijd zo'n 10 doden te betreuren als gevolg van aanvallen door haaien. Omgekeerd worden er per jaar 1 miljoen haaien door de mens gedood. En dat terwijl het een heel belangrijk dier is voor ons ecosysteem!

## Beeldvorming

Net als bij die haaien hebben veel mensen een negatief beeld van AI of van robots door wat ze erover in films gezien hebben. Logisch, want zoals de meeste mensen nog nooit een haai in het echt of in het water gezien hebben, en geloof me: het zijn prachtige beesten om te zien, zo hebben ze vaak ook nog geen robots of bewust AI meegemaakt in het echt.
Kijk maar eens naar onderstaande video die ik maakte tijdens een duik met een blauwe haai op de Azoren.

{{< video https://www.youtube.com/watch?v=nzxLbY6SdT8 >}}

En inmiddels kan ik ook video's laten zien van haaien op de Malediven.

{{< video https://youtu.be/41EbbhqdJJ8?si=kzoXvdLB4lv7B_38 >}}

En hamerhaaien bij Moquera bij de Galagapos Eilanden.

{{< video https://youtu.be/ckFFKlcS8xM?si=ilXRX9KNJHKs6Z5q >}}

En okay, áls je dan toch ergens bang van moet zijn. Dan in ieder geval niet van de haaien!
